version: '3.8'

services:
  # 1. Nginx Webサーバー
  web:
    image: nginx:latest
    ports:
      - "80:80"  # ホストの80番ポートをコンテナの80番ポートにマッピング
    volumes:
      - ./html:/var/www/html  # アプリケーションコードをコンテナにマウント
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf  # Nginx設定ファイル
    depends_on:
      - app
    restart: always

  # 2. PHP-FPM 実行環境
  app:
    build: .  # 同一ディレクトリ内の Dockerfile を使用
    volumes:
      - ./html:/var/www/html
    expose:
      - "9000"  # Webサーバーとの通信用
    restart: always

  # 3. MySQL データベース
  db:
    image: mysql:8.0
    ports:
      - "3306:3306" # (オプション) ホストからもアクセスできるようにポート公開
    environment:
      MYSQL_ROOT_PASSWORD: root_password  # ルートパスワード
      MYSQL_DATABASE: my_database       # 初回作成するデータベース名
      MYSQL_USER: my_user               # ユーザー名
      MYSQL_PASSWORD: user_password     # ユーザーパスワード
    volumes:
      - db_data:/var/lib/mysql  # データ永続化用のボリューム
    restart: always

  # 4. phpMyAdmin DB管理ツール
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    environment:
      PMA_HOST: db              # 接続先のデータベースサービス名
      MYSQL_ROOT_PASSWORD: root_password
    ports:
      - "8080:80"  # ホストの8080番ポートで phpMyAdmin にアクセス
    depends_on:
      - db
    restart: always

volumes:
  db_data:
    driver: local